<?php

namespace Database\Seeders;

use App\Models\master\City;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cities')->delete();
        $cities = [
            // australian capital territory
            ['name' => 'Canberra', 'code' => 'CBA', 'state_id' => 1],
            // new south wales

            ['name' => 'Sydney', 'code' => 'syd', 'state_id' => 2],
            ['name' => 'Central Coast', 'code' => 'cc', 'state_id' => 2],
            ['name' => 'Wollongong', 'code' => 'wlg', 'state_id' => 2],
            ['name' => 'Newcastle', 'code' => 'nwc', 'state_id' => 2],
            ['name' => 'Wagga Wagga', 'code' => 'ww', 'state_id' => 2],
            ['name' => 'Port Macquarie', 'code' => 'pmq', 'state_id' => 2],
            ['name' => 'Bathurst', 'code' => 'bt', 'state_id' => 2],
            ['name' => 'Quakers Hill', 'code' => 'qh', 'state_id' => 2],
            ['name' => 'Armidale', 'code' => 'arm', 'state_id' => 2],
            ['name' => 'Griffith', 'code' => 'gft', 'state_id' => 2],
            ['name' => 'Taree', 'code' => 'tr', 'state_id' => 2],
            ['name' => 'Banora Point', 'code' => 'bp', 'state_id' => 2],
            ['name' => 'Cessnock', 'code' => 'csnk', 'state_id' => 2],
            ['name' => 'Forster', 'code' => 'frsr', 'state_id' => 2],
            ['name' => 'Penrith', 'code' => 'pnr', 'state_id' => 2],
            ['name' => 'Goonellabah', 'code' => 'gnb', 'state_id' => 2],
            ['name' => 'Campbelltown', 'code' => 'cmp', 'state_id' => 2],
            ['name' => 'Rutherford', 'code' => 'rth', 'state_id' => 2],
            ['name' => 'Muswellbrook', 'code' => 'msw', 'state_id' => 2],
            ['name' => 'Grafton', 'code' => 'grft', 'state_id' => 2],
            ['name' => 'Bowral', 'code' => 'bwl', 'state_id' => 2],
            ['name' => 'Casino', 'code' => 'csn', 'state_id' => 2],
            ['name' => 'Parkes', 'code' => 'pks', 'state_id' => 2],
            ['name' => 'Mudgee', 'code' => 'mdg', 'state_id' => 2],
            ['name' => 'Inverell', 'code' => 'ivr', 'state_id' => 2],
            ['name' => 'Nowra', 'code' => 'nwr', 'state_id' => 2],
            ['name' => 'Flemington', 'code' => 'fmg', 'state_id' => 2],
            ['name' => 'Ballina', 'code' => 'bln', 'state_id' => 2],
            ['name' => 'Moss Vale', 'code' => 'mvl', 'state_id' => 2],
            ['name' => 'Springwood', 'code' => 'spw', 'state_id' => 2],
            ['name' => 'Cowra', 'code' => 'cwr', 'state_id' => 2],
            ['name' => 'Tweed Heads', 'code' => 'thd', 'state_id' => 2],
            ['name' => 'Emu Plains', 'code' => 'emp', 'state_id' => 2],
            ['name' => 'Katoomba', 'code' => 'ktm', 'state_id' => 2],
            ['name' => 'Young', 'code' => 'yng', 'state_id' => 2],
            ['name' => 'Kingscliff', 'code' => 'kcl', 'state_id' => 2],
            ['name' => 'Leeton', 'code' => 'ltn', 'state_id' => 2],
            ['name' => 'Blaxland', 'code' => 'bxl', 'state_id' => 2],
            ['name' => 'Sanctuary Point', 'code' => 'scp', 'state_id' => 2],
            ['name' => 'Moama', 'code' => 'mma', 'state_id' => 2],
            ['name' => 'Merrimac', 'code' => 'mmc', 'state_id' => 2],
            ['name' => 'Moree', 'code' => 'mre', 'state_id' => 2],
            ['name' => 'Murwillumbah', 'code' => 'mwb', 'state_id' => 2],
            ['name' => 'Bomaderry', 'code' => 'bmd', 'state_id' => 2],
            ['name' => 'Helensburgh', 'code' => 'hlb', 'state_id' => 2],
            ['name' => 'Deniliquin', 'code' => 'dnq', 'state_id' => 2],
            ['name' => 'Lennox Head', 'code' => 'lnx', 'state_id' => 2],
            ['name' => 'Nambucca Heads', 'code' => 'nbh', 'state_id' => 2],
            ['name' => 'Wauchope', 'code' => 'wch', 'state_id' => 2],
            ['name' => 'Tumut', 'code' => 'tmt', 'state_id' => 2],
            ['name' => 'Tuncurry', 'code' => 'tnc', 'state_id' => 2],
            ['name' => 'Yamba', 'code' => 'ymb', 'state_id' => 2],
            ['name' => 'Kurri Kurri', 'code' => 'kkr', 'state_id' => 2],
            ['name' => 'Yass', 'code' => 'yss', 'state_id' => 2],
            ['name' => 'Mittagong', 'code' => 'mtgg', 'state_id' => 2],
            ['name' => 'Cootamundra', 'code' => 'ctm', 'state_id' => 2],
            ['name' => 'Narrabri', 'code' => 'nbr', 'state_id' => 2],
            ['name' => 'Corowa', 'code' => 'crw', 'state_id' => 2],
            ['name' => 'Richmond', 'code' => 'rch', 'state_id' => 2],
            ['name' => 'Woolgoolga', 'code' => 'wlga', 'state_id' => 2],
            ['name' => 'Glen Innes', 'code' => 'gli', 'state_id' => 2],
            ['name' => 'Alstonville', 'code' => 'ast', 'state_id' => 2],
            ['name' => 'Worragee', 'code' => 'wrg', 'state_id' => 2],
            ['name' => 'Glenbrook', 'code' => 'glb', 'state_id' => 2],
            ['name' => 'Tahmoor', 'code' => 'tah', 'state_id' => 2],
            ['name' => 'Scone', 'code' => 'scn', 'state_id' => 2],
            ['name' => 'Kiama Downs', 'code' => 'kdm', 'state_id' => 2],
            ['name' => 'Hazelbrook', 'code' => 'hzb', 'state_id' => 2],
            ['name' => 'Lithgow', 'code' => 'ltg', 'state_id' => 2],
            ['name' => 'Salamander Bay', 'code' => 'slb', 'state_id' => 2],
            ['name' => 'Albury', 'code' => 'alb', 'state_id' => 2],
            ['name' => 'Wingham', 'code' => 'wng', 'state_id' => 2],
            ['name' => 'Old Bar', 'code' => 'olb', 'state_id' => 2],
            ['name' => 'Wyong', 'code' => 'wyg', 'state_id' => 2],
            ['name' => 'Wellington', 'code' => 'welt', 'state_id' => 2],
            ['name' => 'Thirlmere', 'code' => 'thm', 'state_id' => 2],
            ['name' => 'Temora', 'code' => 'tem', 'state_id' => 2],
            ['name' => 'The Entrance', 'code' => 'ten', 'state_id' => 2],
            ['name' => 'Gerringong', 'code' => 'grg', 'state_id' => 2],
            ['name' => 'Picton', 'code' => 'pct', 'state_id' => 2],
            ['name' => 'Narrandera', 'code' => 'nra', 'state_id' => 2],
            ['name' => 'Suffolk Park', 'code' => 'sfp', 'state_id' => 2],
            ['name' => 'Weston', 'code' => 'wst', 'state_id' => 2],
            ['name' => 'Sawtell', 'code' => 'swt', 'state_id' => 2],
            ['name' => 'Silverdale', 'code' => 'svd', 'state_id' => 2],
            ['name' => 'Bay View', 'code' => 'bvw', 'state_id' => 2],
            ['name' => 'Lismore', 'code' => 'lsm', 'state_id' => 2],
            ['name' => 'Merimbula', 'code' => 'mrbl', 'state_id' => 2],
            ['name' => 'Lake Cathie', 'code' => 'lkec', 'state_id' => 2],
            ['name' => 'Cobar', 'code' => 'cbr', 'state_id' => 2],
            ['name' => 'Bellingen', 'code' => 'blg', 'state_id' => 2],
            ['name' => 'Mullumbimby', 'code' => 'mlb', 'state_id' => 2],
            ['name' => 'Tura Beach', 'code' => 'trb', 'state_id' => 2],
            ['name' => 'Eden', 'code' => 'edn', 'state_id' => 2],
            ['name' => 'Bogangar', 'code' => 'bggr', 'state_id' => 2],
            ['name' => 'Shoalhaven Heads', 'code' => 'shh', 'state_id' => 2],
            ['name' => 'Blayney', 'code' => 'bly', 'state_id' => 2],
            ['name' => 'Wilton', 'code' => 'wlt', 'state_id' => 2],
            ['name' => 'Terranora', 'code' => 'trn', 'state_id' => 2],
            ['name' => 'Saint Georges Basin', 'code' => 'sgb', 'state_id' => 2],
            ['name' => 'Culburra', 'code' => 'clr', 'state_id' => 2],
            ['name' => 'Tea Gardens', 'code' => 'tg', 'state_id' => 2],
            ['name' => 'Bonny Hills', 'code' => 'bnh', 'state_id' => 2],
            ['name' => 'Urunga', 'code' => 'urg', 'state_id' => 2],
            ['name' => 'Vincentia', 'code' => 'vnt', 'state_id' => 2],
            ['name' => 'West Wyalong', 'code' => 'wwy', 'state_id' => 2],
            ['name' => 'Howlong', 'code' => 'hwl', 'state_id' => 2],
            ['name' => 'Lawson', 'code' => 'lwn', 'state_id' => 2],
            ['name' => 'Narooma', 'code' => 'nrm', 'state_id' => 2],
            ['name' => 'Quirindi', 'code' => 'qrn', 'state_id' => 2],
            ['name' => 'Condobolin', 'code' => 'cnd', 'state_id' => 2],
            ['name' => 'Aberdare', 'code' => 'abd', 'state_id' => 2],
            ['name' => 'Gilgandra', 'code' => 'gldr', 'state_id' => 2],
            ['name' => 'Sandy Beach', 'code' => 'snb', 'state_id' => 2],
            ['name' => 'Hill Top', 'code' => 'hlt', 'state_id' => 2],
            ['name' => 'Jindabyne', 'code' => 'jdn', 'state_id' => 2],
            ['name' => 'The Oaks', 'code' => 'tok', 'state_id' => 2],
            ['name' => 'Heddon Greta', 'code' => 'hdg', 'state_id' => 2],
            ['name' => 'Grenfell', 'code' => 'grf', 'state_id' => 2],
            ['name' => 'Bangalow', 'code' => 'bnl', 'state_id' => 2],
            ['name' => 'Manilla', 'code' => 'mnl', 'state_id' => 2],
            ['name' => 'Camden Haven', 'code' => 'cmd', 'state_id' => 2],
            ['name' => 'Wallerawang', 'code' => 'wlw', 'state_id' => 2],
            ['name' => 'Mulwala', 'code' => 'mlw', 'state_id' => 2],
            ['name' => 'Windsor', 'code' => 'wnd', 'state_id' => 2],
            ['name' => 'Batehaven', 'code' => 'bth', 'state_id' => 2],
            ['name' => 'Brunswick Heads', 'code' => 'bwh', 'state_id' => 2],
            ['name' => 'Denman', 'code' => 'dnm', 'state_id' => 2],
            ['name' => 'Bourke', 'code' => 'brk', 'state_id' => 2],
            ['name' => 'Tathra', 'code' => 'ttr', 'state_id' => 2],
            ['name' => 'Canowindra', 'code' => 'cnw', 'state_id' => 2],
            ['name' => 'Walgett', 'code' => 'wlgt', 'state_id' => 2],
            ['name' => 'Surfside', 'code' => 'sfs', 'state_id' => 2],
            ['name' => 'Greenwell Point', 'code' => 'gnp', 'state_id' => 2],
            ['name' => 'Valley Heights', 'code' => 'vht', 'state_id' => 2],
            ['name' => 'Oakdale', 'code' => 'okd', 'state_id' => 2],
            ['name' => 'Mollymook', 'code' => 'mlm', 'state_id' => 2],
            //northern territory
            ['name' => 'Darwin', 'code' => 'dar', 'state_id' => 3],
            ['name' => 'Palmerston', 'code' => 'pal', 'state_id' => 3],
            //queensland

            ['name' => 'Brisbane', 'code' => 'brs', 'state_id' => 4],
            ['name' => 'Gold Coast', 'code' => 'gld', 'state_id' => 4],
            ['name' => 'Ipswich', 'code' => 'ips', 'state_id' => 4],
            ['name' => 'Townsville', 'code' => 'tnv', 'state_id' => 4],
            ['name' => 'Cairns', 'code' => 'crn', 'state_id' => 4],
            ['name' => 'Toowoomba', 'code' => 'twb', 'state_id' => 4],
            ['name' => 'Mackay', 'code' => 'mky', 'state_id' => 4],
            ['name' => 'Hervey Bay', 'code' => 'hvb', 'state_id' => 4],
            ['name' => 'Buderim', 'code' => 'bdm', 'state_id' => 4],
            ['name' => 'Caloundra', 'code' => 'cld', 'state_id' => 4],
            ['name' => 'Gladstone', 'code' => 'glt', 'state_id' => 4],
            ['name' => 'Southport', 'code' => 'stp', 'state_id' => 4],
            ['name' => 'Maroochydore', 'code' => 'mrc', 'state_id' => 4],
            ['name' => 'Ormeau', 'code' => 'orm', 'state_id' => 4],
            ['name' => 'Nambour', 'code' => 'nmb', 'state_id' => 4],
            ['name' => 'Corinda', 'code' => 'crd', 'state_id' => 4],
            ['name' => 'Kingaroy', 'code' => 'kgr', 'state_id' => 4],
            ['name' => 'Andergrove', 'code' => 'adgv', 'state_id' => 4],
            ['name' => 'Bargara', 'code' => 'bgr', 'state_id' => 4],
            ['name' => 'Mareeba', 'code' => 'marb', 'state_id' => 4],
            ['name' => 'Beenleigh', 'code' => 'bnlh', 'state_id' => 4],
            ['name' => 'Charters Towers', 'code' => 'cht', 'state_id' => 4],
            ['name' => 'Urraween', 'code' => 'urw', 'state_id' => 4],
            ['name' => 'Bongaree', 'code' => 'bng', 'state_id' => 4],
            ['name' => 'Burpengary', 'code' => 'brp', 'state_id' => 4],
            ['name' => 'Waterford', 'code' => 'wfd', 'state_id' => 4],
            ['name' => 'North Mackay', 'code' => 'nmk', 'state_id' => 4],
            ['name' => 'Cannonvale', 'code' => 'cnv', 'state_id' => 4],
            ['name' => 'Point Vernon', 'code' => 'ptv', 'state_id' => 4],
            ['name' => 'Palmwoods', 'code' => 'pmw', 'state_id' => 4],
            ['name' => 'Bucasia', 'code' => 'bcs', 'state_id' => 4],
            ['name' => 'Glenella', 'code' => 'gln', 'state_id' => 4],
            ['name' => 'Rasmussen', 'code' => 'rsm', 'state_id' => 4],
            ['name' => 'Deeragun', 'code' => 'drg', 'state_id' => 4],
            ['name' => 'Peregian Beach', 'code' => 'pgb', 'state_id' => 4],
            ['name' => 'Scarness', 'code' => 'scr', 'state_id' => 4],
            ['name' => 'Proserpine', 'code' => 'prs', 'state_id' => 4],
            ['name' => 'Beachmere', 'code' => 'bcm', 'state_id' => 4],
            ['name' => 'Thursday Island', 'code' => 'tsi', 'state_id' => 4],
            ['name' => 'Freshwater', 'code' => 'frs', 'state_id' => 4],
            ['name' => 'Kawana Waters', 'code' => 'kww', 'state_id' => 4],
            ['name' => 'Yaroomba', 'code' => 'yrb', 'state_id' => 4],
            ['name' => 'Innisfail', 'code' => 'inf', 'state_id' => 4],
            // South Australia
            ['name' => 'Adelaide', 'code' => 'adl', 'state_id' => 5],
            ['name' => 'Mount Gambier', 'code' => 'mtg', 'state_id' => 5],
            ['name' => 'Whyalla', 'code' => 'wyl', 'state_id' => 5],
            ['name' => 'Murray Bridge', 'code' => 'mrb', 'state_id' => 5],
            ['name' => 'Mount Barker', 'code' => 'mtb', 'state_id' => 5],
            ['name' => 'Port Augusta', 'code' => 'pta', 'state_id' => 5],
            ['name' => 'Strathalbyn', 'code' => 'str', 'state_id' => 5],
            ['name' => 'Nuriootpa', 'code' => 'nur', 'state_id' => 5],
            ['name' => 'Nairne', 'code' => 'nrn', 'state_id' => 5],
            ['name' => 'Encounter Bay', 'code' => 'enc', 'state_id' => 5],
            ['name' => 'Millicent', 'code' => 'mlc', 'state_id' => 5],
            ['name' => 'Renmark', 'code' => 'rnk', 'state_id' => 5],
            ['name' => 'Tanunda', 'code' => 'tnn', 'state_id' => 5],
            ['name' => 'Victor Harbor', 'code' => 'vhr', 'state_id' => 5],
            ['name' => 'Berri', 'code' => 'brr', 'state_id' => 5],
            ['name' => 'Loxton', 'code' => 'lxt', 'state_id' => 5],
            ['name' => 'Roxby Downs', 'code' => 'rxd', 'state_id' => 5],
            ['name' => 'Aldgate', 'code' => 'adg', 'state_id' => 5],
            ['name' => 'McLaren Vale', 'code' => 'mcv', 'state_id' => 5],
            ['name' => 'Stirling', 'code' => 'stl', 'state_id' => 5],
            ['name' => 'Kapunda', 'code' => 'kpnd', 'state_id' => 5],
            ['name' => 'Goolwa', 'code' => 'glw', 'state_id' => 5],
            ['name' => 'Hahndorf', 'code' => 'hnd', 'state_id' => 5],
            ['name' => 'Willunga', 'code' => 'wilg', 'state_id' => 5],
            ['name' => 'Williamstown', 'code' => 'wmt', 'state_id' => 5],
            ['name' => 'Freeling', 'code' => 'frl', 'state_id' => 5],
            ['name' => 'Lobethal', 'code' => 'lbt', 'state_id' => 5],
            ['name' => 'Barmera', 'code' => 'bmr', 'state_id' => 5],
            ['name' => 'Woodside', 'code' => 'wds', 'state_id' => 5],
            ['name' => 'Lyndoch', 'code' => 'lyn', 'state_id' => 5],
            ['name' => 'Waikerie', 'code' => 'wkr', 'state_id' => 5],
            // Tasmania

            ['name' => 'Hobart', 'code' => 'hob', 'state_id' => 6],
            ['name' => 'Launceston', 'code' => 'lnc', 'state_id' => 6],
            ['name' => 'Burnie', 'code' => 'bur', 'state_id' => 6],
            ['name' => 'Kingston', 'code' => 'kng', 'state_id' => 6],
            ['name' => 'Ulverstone', 'code' => 'ulv', 'state_id' => 6],
            ['name' => 'New Norfolk', 'code' => 'nnf', 'state_id' => 6],
            ['name' => 'Wynyard', 'code' => 'wyn', 'state_id' => 6],
            ['name' => 'George Town', 'code' => 'gtn', 'state_id' => 6],
            ['name' => 'Latrobe', 'code' => 'ltr', 'state_id' => 6],
            ['name' => 'Legana', 'code' => 'leg', 'state_id' => 6],
            ['name' => 'Somerset', 'code' => 'som', 'state_id' => 6],
            ['name' => 'Longford', 'code' => 'lgf', 'state_id' => 6],
            ['name' => 'Perth', 'code' => 'pert', 'state_id' => 6],
            ['name' => 'Penguin', 'code' => 'png', 'state_id' => 6],
            ['name' => 'Smithton', 'code' => 'smt', 'state_id' => 6],
            ['name' => 'Deloraine', 'code' => 'del', 'state_id' => 6],
            ['name' => 'Margate', 'code' => 'mrg', 'state_id' => 6],
            ['name' => 'Dodges Ferry', 'code' => 'dfy', 'state_id' => 6],
            ['name' => 'Hadspen', 'code' => 'hsp', 'state_id' => 6],
            ['name' => 'Queenstown', 'code' => 'qtn', 'state_id' => 6],
            ['name' => 'Westbury', 'code' => 'wby', 'state_id' => 6],
            ['name' => 'Seven Mile Beach', 'code' => 'smb', 'state_id' => 6],
            ['name' => 'Evandale', 'code' => 'evn', 'state_id' => 6],
            // victoria

            ['name' => 'Melbourne', 'code' => 'mel', 'state_id' => 7],
            ['name' => 'Cranbourne', 'code' => 'cnb', 'state_id' => 7],
            ['name' => 'Geelong', 'code' => 'geo', 'state_id' => 7],
            ['name' => 'Ballarat', 'code' => 'bal', 'state_id' => 7],
            ['name' => 'Bendigo', 'code' => 'ben', 'state_id' => 7],
            ['name' => 'Pakenham', 'code' => 'pak', 'state_id' => 7],
            ['name' => 'Frankston', 'code' => 'frk', 'state_id' => 7],
            ['name' => 'Sunbury', 'code' => 'sun', 'state_id' => 7],
            ['name' => 'Dandenong', 'code' => 'dan', 'state_id' => 7],
            ['name' => 'Warrnambool', 'code' => 'war', 'state_id' => 7],
            ['name' => 'Traralgon', 'code' => 'tran', 'state_id' => 7],
            ['name' => 'Mount Eliza', 'code' => 'mtea', 'state_id' => 7],
            ['name' => 'Lara', 'code' => 'lar', 'state_id' => 7],
            ['name' => 'Horsham', 'code' => 'hor', 'state_id' => 7],
            ['name' => 'Wallan', 'code' => 'wal', 'state_id' => 7],
            ['name' => 'Barwon Heads', 'code' => 'bhd', 'state_id' => 7],
            ['name' => 'Morwell', 'code' => 'mor', 'state_id' => 7],
            ['name' => 'Leopold', 'code' => 'leopd', 'state_id' => 7],
            ['name' => 'Swan Hill', 'code' => 'swh', 'state_id' => 7],
            ['name' => 'Mount Evelyn', 'code' => 'mte', 'state_id' => 7],
            ['name' => 'Colac', 'code' => 'col', 'state_id' => 7],
            ['name' => 'Rye', 'code' => 'rye', 'state_id' => 7],
            ['name' => 'Mooroopna', 'code' => 'moo', 'state_id' => 7],
            ['name' => 'Maryborough', 'code' => 'mar', 'state_id' => 7],
            ['name' => 'Narre Warren North', 'code' => 'nwn', 'state_id' => 7],
            ['name' => 'Clifton Springs', 'code' => 'clp', 'state_id' => 7],
            ['name' => 'Castlemaine', 'code' => 'csm', 'state_id' => 7],
            ['name' => 'Kyabram', 'code' => 'kya', 'state_id' => 7],
            ['name' => 'Dromana', 'code' => 'dro', 'state_id' => 7],
            ['name' => 'Seymour', 'code' => 'sey', 'state_id' => 7],
            ['name' => 'Lakes Entrance', 'code' => 'lke', 'state_id' => 7],
            ['name' => 'Leongatha', 'code' => 'leoa', 'state_id' => 7],
            ['name' => 'Stawell', 'code' => 'stw', 'state_id' => 7],
            ['name' => 'Whittlesea', 'code' => 'wht', 'state_id' => 7],
            ['name' => 'Inverloch', 'code' => 'inv', 'state_id' => 7],
            ['name' => 'Churchill', 'code' => 'chu', 'state_id' => 7],
            ['name' => 'Maffra', 'code' => 'maf', 'state_id' => 7],
            ['name' => 'Broadford', 'code' => 'brd', 'state_id' => 7],
            ['name' => 'Drysdale', 'code' => 'dry', 'state_id' => 7],
            ['name' => 'Tatura', 'code' => 'tat', 'state_id' => 7],
            ['name' => 'Cockatoo', 'code' => 'cok', 'state_id' => 7],
            ['name' => 'Mansfield', 'code' => 'manfd', 'state_id' => 7],
            ['name' => 'Korumburra', 'code' => 'kor', 'state_id' => 7],
            ['name' => 'Trafalgar', 'code' => 'trar', 'state_id' => 7],
            ['name' => 'Pearcedale', 'code' => 'pea', 'state_id' => 7],
            ['name' => 'Numurkah', 'code' => 'num', 'state_id' => 7],
            ['name' => 'Buninyong', 'code' => 'bun', 'state_id' => 7],
            ['name' => 'Kerang', 'code' => 'ker', 'state_id' => 7],
            ['name' => 'Paynesville', 'code' => 'pay', 'state_id' => 7],
            ['name' => 'Maddingley', 'code' => 'mad', 'state_id' => 7],
            ['name' => 'Port Fairy', 'code' => 'pfa', 'state_id' => 7],
            ['name' => 'Koo-Wee-Rup', 'code' => 'koo', 'state_id' => 7],
            ['name' => 'Euroa', 'code' => 'eur', 'state_id' => 7],
            ['name' => 'Red Cliffs', 'code' => 'red', 'state_id' => 7],
            ['name' => 'Woori Yallock', 'code' => 'woo', 'state_id' => 7],
            ['name' => 'Camperdown', 'code' => 'cam', 'state_id' => 7],
            ['name' => 'McCrae', 'code' => 'mcc', 'state_id' => 7],
            ['name' => 'North Wonthaggi', 'code' => 'nwni', 'state_id' => 7],
            ['name' => 'Launching Place', 'code' => 'lau', 'state_id' => 7],
            ['name' => 'Rutherglen', 'code' => 'rut', 'state_id' => 7],
            ['name' => 'Beaconsfield Upper', 'code' => 'bcu', 'state_id' => 7],
            ['name' => 'Baxter', 'code' => 'bax', 'state_id' => 7],
            ['name' => 'Saint Arnaud', 'code' => 'sar', 'state_id' => 7],
            ['name' => 'Orbost', 'code' => 'orb', 'state_id' => 7],
            ['name' => 'Wattleglen', 'code' => 'wat', 'state_id' => 7],
            ['name' => 'Yarram', 'code' => 'yarm', 'state_id' => 7],
            ['name' => 'Curlewis', 'code' => 'cur', 'state_id' => 7],
            ['name' => 'Nathalia', 'code' => 'nat', 'state_id' => 7],
            ['name' => 'Cobden', 'code' => 'cob', 'state_id' => 7],
            ['name' => 'Yarragon', 'code' => 'yar', 'state_id' => 7],
            ['name' => 'San Remo', 'code' => 'san', 'state_id' => 7],
            ['name' => 'Yallourn North', 'code' => 'ynr', 'state_id' => 7],
            ['name' => 'Wahgunyah', 'code' => 'wah', 'state_id' => 7],
            //Western Australia
            ['name' => 'Perth', 'code' => 'perh', 'state_id' => 8],
            ['name' => 'Mandurah', 'code' => 'man', 'state_id' => 8],
            ['name' => 'Australind', 'code' => 'aus', 'state_id' => 8],
            ['name' => 'Fremantle', 'code' => 'fre', 'state_id' => 8],
            ['name' => 'Boulder', 'code' => 'bou', 'state_id' => 8],
            ['name' => 'Esperance', 'code' => 'esp', 'state_id' => 8],
            ['name' => 'Drummond Cove', 'code' => 'drc', 'state_id' => 8],

        ];

        foreach ($cities as $city) {
            City::create($city);
        }
    }
}
